[tool.poetry]
name = "bvar-impulse-responses-jk-2020"
version = "0.1.0"
description = ""
authors = ["Rubén Fernández Fuertes <fernandezfuertesruben@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^1.26.0"
pandas = "^2.0.0"
scipy = "^1.11.0"

[tool.poetry.scripts]
get-data = "mains.get_data:main"
run-bvar = "mains.run_bvar:run_var_analysis"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

