[tool.poetry]
name = "bvar-impulse-responses-jk-2020"
version = "0.1.0"
description = ""
authors = ["Rubén Fernández Fuertes <fernandezfuertesruben@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
